version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=main.py
      - DEBUG=False  # Optional additional environment variable
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]  # Optional health check
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped